### ISSUE TITLE
When going from netconf_config to ansible.netcommon.netconf_config the module errors out. 

### ISSUE THREAD

**Issue by redhatpat** [ansible-collections/ansible.netcommon#130]
##### SUMMARY
When going from netconf_config to ansible.netcommon.netconf_config the module errors out. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.netcommon.netconf_config

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /home/ec2-user/ansible-git-repo-np/ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/venv/ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/ec2-user/venv/ansible/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```DEFAULT_CALLBACK_WHITELIST(/home/ec2-user/ansible-git-repo-np/ansible/ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles']
DEFAULT_STRATEGY(/home/ec2-user/ansible-git-repo-np/ansible/ansible.cfg) = free

```

##### OS / ENVIRONMENT

task is being run against IOS XE 16.12.02

##### STEPS TO REPRODUCE

replacing netconf_config with ansible.netcommon.netconf_config

```
- name: Configure interfaces via NETCONF Cisco YANG Model
   ansible.netcommon.netconf_config:
     content: "{{ lookup('template', './cisco_interfaces_l2.j2') }}"
     target: candidate
     timeout: 300
     commit: yes
     validate: no

```

##### EXPECTED RESULTS

Update the config on the cisco ios xe device

##### ACTUAL RESULTS

Get an error

```
            "host": null,
            "hostkey_verify": true,
            "lock": "always",
            "look_for_keys": true,
            "password": null,
            "port": 830,
            "save": false,
            "source_datastore": null,
            "src": null,
            "ssh_keyfile": null,
            "target": "candidate",
            "timeout": 300,
            "username": null,
            "validate": false
        }
    },
    "msg": "content value should have xml string with <config> tag as root"
}

```
