### ISSUE TITLE
[ansible-pylibssh] Privilege escalation not working for linux host

### ISSUE THREAD

**Issue by ganeshrn** [ansible-collections/ansible.netcommon#165]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
Privilege escalation not working for Linux host using libssh transport
```

##### CONFIGURATION

```paste below

[persistent_connection]
connect_timeout = 100
command_timeout = 100
ssh_type = libssh
```

##### STEPS TO REPRODUCE

```yaml
- hosts: fedora
  gather_facts: no
  connection: ansible.netcommon.libssh

  tasks:
  - name: run commands
    command:
      cmd: "{{ item }}"
    loop:
    - "ls -al"
    become: true
    register: result
```

##### ACTUAL RESULTS

```paste below
Privilege escalation fails
```
