### ISSUE TITLE
Private key based authentication not working with libssh transport

### ISSUE THREAD

**Issue by ganeshrn** [ansible-collections/ansible.netcommon#168]
##### SUMMARY

https://f11a368f49a99aa94a4b-a8197e288d38b758f0e34de77fff7fd5.ssl.cf5.rackcdn.com/183/d62b80e4b4165d58542bf44b577e899c5d2a1383/check/ansible-test-network-integration-ios-network_cli-libssh-python36/ab730ab/controller/ansible-debug.txt

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

connection/libssh.py

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ios
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Ensure ssh key is not world readable
      file:
        path: './files/test_rsa'
        mode: 384

    - name: Create user with sshkey
      cisco.ios.ios_user:
        name: ssh_user
        privilege: 15
        role: network-operator
        state: present
        sshkey: "{{ lookup('file', './files/test_rsa.pub') }}"

    - name: reset connection with {{ ansible_user }
      meta: reset_connection

    - name: test sshkey login for {{ ansible_user }} user
      cisco.ios.ios_command:
        commands:
          - show version
      vars:
        ansible_user: ssh_user
        ansible_private_key_file: "./files/test_rsa"
```

##### EXPECTED RESULTS

Should run without failure

##### ACTUAL RESULTS

Fail with error

```paste below
    "msg": "ssh connection failed: Failed to authenticate public key: Access denied for 'publickey'. Authentication that can continue: publickey,keyboard-interactive,password"

```
