### ISSUE TITLE
ipaddr filter cannot be used in Ansible 2.9.15 on Ubuntu 16.04

### ISSUE THREAD

**Issue by relyt0925** [ansible-collections/ansible.netcommon#179]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

netaddr/ipaddr filter 

##### ANSIBLE VERSION

```paste below
Ansible 2.9.15
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

Try to use ipaddr filter in a template like 
```
<10.93.34.41> EXEC /bin/sh -c '\''rm -f -r /root/.ansible/tmp/ansible-tmp-1604698086.2652125-6320-187974680628152/ > /dev/null 2>&1 && sleep 0'\''
fatal: [10.93.34.41]: FAILED! => {
    "changed": false,
    "msg": "AnsibleError: template error while templating string: no filter named '\''ipaddr'\''. String: # 
<!--- Paste example playbooks or commands between quotes below -->
```

##### EXPECTED RESULTS

ipaddr filter to be available when netaddr python package is installed

##### ACTUAL RESULTS

ipaddr filter is not available in ansible 2.9.15 on Ubuntu 16.04

```paste below

```

Note: I do not see the same regression on RHEL 7 or Ubuntu 18.04

**Comment by relyt0925** [comment]
I see this note about it migrating to netcommon but wouldn't expect it to break on a patch update 
https://galaxy.ansible.com/ansible/netcommon?extIdCarryOver=true&sc_cid=701f2000001OH6uAAG

I can replicate with this playbook on an ubuntu 16.04 machine:
```
apt-get install -y build-essential libffi-dev libssl-dev python3-pip
pip3 install ansible==2.9.15
pip3 install netaddr
pip3 install jmespath
ansible-playbook -vvv -i "localhost," -c local testplay.yaml -e ansible_python_interpreter=/usr/bin/python3
```

Where testplay.yaml is

```
- hosts: all
  tasks:
    - name: get existing svc
      set_fact:
        k8s_service_ip_range: "172.20.0.0/16"

    - name: get existing svc
      set_fact:
        cluster_dns: "{{ k8s_service_ip_range|ipaddr('10')|ipaddr('address') }}"
```
