### ISSUE TITLE
connect and command timeout ignored 

### ISSUE THREAD

**Issue by maxrainer** [ansible-collections/ansible.netcommon#269]
##### SUMMARY
Timeouts defined as vars directly under tasks are ignored. 
All timeouts must be defined in ansible.cfg.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Tested with latest cisco.nxos collection. 
Tested with nxos_command and nxos_install_os.
But might effect all collections and all modules using netcommon.

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /Users/mrainer/Documents/dev/ansible/networking/roles/network-update/ansible.cfg
  configured module search path = ['/Users/mrainer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mrainer/venv/network/lib/python3.8/site-packages/ansible
  executable location = /Users/mrainer/venv/network/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/mrainer/Documents/dev/ansible/networking/roles/network-update/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/mrainer/Documents/dev/ansible/networking/roles/network-update/ansible.cfg) = 600
PERSISTENT_CONNECT_TIMEOUT(/Users/mrainer/Documents/dev/ansible/networking/roles/network-update/ansible.cfg) = 600
SHOW_CUSTOM_STATS(/Users/mrainer/Documents/dev/ansible/networking/roles/network-update/ansible.cfg) = True
```

##### OS / ENVIRONMENT

tested on Tower RHEL 8.3 and MacOS. Always same problem. 

##### STEPS TO REPRODUCE

Command timeout and connect timeout are ignored when defined directly in tasks. (stay 30s)
Only when defined in ansible.cfg under section [persistent_connection] it works.

```yaml
  - name: check configuration compatibility to new image
    cisco.nxos.nxos_command:
      commands: "show incompatibility-all nxos bootflash:/{{ update_image_name_new }}"
      wait_for: result[0] contains No incompatibility configurations
      retries: 1
    vars:
      - ansible_command_timeout: 600
      - ansible_connect_timeout: 600
    register: _incompatibility
```

##### EXPECTED RESULTS

https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#command-timeout

##### ACTUAL RESULTS

```paste below

```

**Comment by tin-ot** [comment]
Hello, 

I am facing the same issue with the plugin nxos_install_os,
And I can't have the timeouts set globally.

Is there anything that can be done to avoid the bug and set the timeout as a variable specifically for the given task ?

**Comment by jiholland** [comment]
Experiencing the same problem with ansible.netcommon 2.5.0 and ansible version 2.9.27

---
- name: gather facts
  cisco.ios.ios_facts:
    gather_subset: all
  vars:
    ansible_command_timeout: 35
...
=> {"changed": false, "msg": "timed out"}


However, in my case the problem only applies when increasing the timeout above the default 30 seconds.

---
- name: gather facts
  cisco.ios.ios_facts:
    gather_subset: all
  vars:
    ansible_command_timeout: 2
...
=> {"changed": false, "msg": "command timeout triggered, timeout value is 2 secs\nSee the timeout settings options in the Network Debug and Troubleshooting Guide."}

**Comment by jknight-netscout** [comment]
I've found that a workaround is to use `meta: reset_connection` before and after the task you'd like to increase the timeout for.

My example task, which seemed to work

```
- name: Workaround to bump timeout
  meta: reset_connection

- name: Find any required upgrades for modules
  register: epld_upgrade_required
    vars:
      ansible_command_timeout: 90
    ansible.netcommon.cli_command:
      command: "show install all impact epld bootflash:{{ epld_file }} | json"

- name: Workaround, back to default timeout
  meta: reset_connection
```
Before using this workaround, the command would timeout at 30 seconds even though for this task I had the timeout set to 90 seconds.  After this workaround, my command correctly waits longer and no longer fails.


The problem is network_cli.py will only read in the timeout variable on a new ssh connection. If it's not the first task in the playbook, and therefore you have an existing ssh connection already, the plugin will not update the command_timeout variable and continue to use the value used when the session was first established.

https://github.com/ansible-collections/ansible.netcommon/blob/1169d48faab1ec937d945b947c45ba40de9597f9/plugins/connection/network_cli.py#L583
https://github.com/ansible-collections/ansible.netcommon/blob/1169d48faab1ec937d945b947c45ba40de9597f9/plugins/connection/network_cli.py#L587

If you kill/reset the connection before your task, then the variable is read in and used when it establishes the new connection. Then you can kill/reset after so that the rest of your tasks still use the global timeout.
