### ISSUE TITLE
ansible.netcommon.vlan_parser fails on empty list

### ISSUE THREAD

**Issue by u1735067** [ansible-collections/ansible.netcommon#302]
##### SUMMARY

vlan_parser fails with `list index out of range` on empty list

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Filter `ansible.netcommon.vlan_parser`

##### ANSIBLE VERSION

```
ansible 2.10.11
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/projects/ansible-2.10/lib/python3.8/site-packages/ansible
  executable location = /home/me/projects/ansible-2.10/bin/ansible
  python version = 3.8.1 (default, Feb 25 2020, 09:21:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### COLLECTION VERSION

```
Collection             Version
---------------------- -------
ansible.netcommon      *
```
(v2.1.0 from CHANGELOG.rst)

##### STEPS TO REPRODUCE

```yaml
---
- name: TEST
  hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.debug:
        msg: "{{ [] | ansible.netcommon.vlan_parser | default('none', true) }}"
```

##### EXPECTED RESULTS

Return an empty string or None or False or the value of an extra `empty_value` argument.

##### ACTUAL RESULTS

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range`

```paste below
File "collections.galaxy/ansible_collections/ansible/netcommon/plugins/filter/network.py", line 458, in vlan_parser
    if sorted_list[0] < 1 or sorted_list[-1] > 4094:
IndexError: list index out of range
```

##### Workaround

Use `list_compress` from Arista AVD (https://github.com/aristanetworks/ansible-avd/blob/v2.2.1/ansible_collections/arista/avd/plugins/filter/list_compress.py)
