### ISSUE TITLE
Add test-option parameters

### ISSUE THREAD

**Issue by jerem0808** [ansible-collections/ansible.netcommon#303]
##### SUMMARY

I would like to be able to use the parameters test-option from the plugin netcommon.netconf_config
##### ISSUE TYPE
- Feature Idea
test-option parameters available in netconf_config
##### ADDITIONAL INFORMATION

Exactly like default-operation or error-option we should be able to have the option "test-option" as described in [rfc6241](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2)
I'm working on a node where we only have the running datastore. I'd like to validate my configuration without enabling it. I am new to Ansible / netcommon but I think that test-option would solved what I need. 

```yaml
- hosts: deployment
  tasks:
  - name: Validate config
    ansible.netcommon.netconf_config:
      test-option: test-only
      content: "{{ lookup('file', './output_rendered.xml') }}"
```
