### ISSUE TITLE
Unable to use TTP template to parse variable holding command output

### ISSUE THREAD

**Issue by refriedjello** [ansible-collections/ansible.netcommon#328]
##### SUMMARY
Using Ansible to execute a TTP template to parse device output when that output is stored in a variable produces error about unable to call .splitlines method against the list of output, as per documentation. Pointing directly at the list element containing the output produces a different error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.netcommon.native

##### ANSIBLE VERSION
```
ansible [core 2.11.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/modules', '/opt/netops-lib/ansible/modules', '/usr/local/lib/python3.6/site-packages/napalm-ansible']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jul 22 2021, 09:51:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.2.0

# /etc/ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.3.0
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/collections']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/modules', '/opt/netops-lib/ansible/modules', '/usr/local/lib/python3.6/site-packages/napalm-ansible']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/home/refried.jello/tmp/ttp/int3', '/etc/ansible/roles', '/etc/ansible/provisioning', '/etc/ansible/config_pull', '/etc/ansible/provisionin
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/local/bin/python3.9
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.15.2.el7.x86_64
      Architecture: x86-64

Device target: Cisco NCS-5501, Cisco IOS XR Software, Version 6.6.3

##### STEPS TO REPRODUCE
Use Ansible command module for given NOS to execute the 'show run' command and store the output in a variable. Then use TTP to parse that variable output to produce TTP output.

```
- hosts: all
  connection: network_cli
  gather_facts: no
  become: no

  tasks:

  - name: "IOS-XR - Pull running-config"
    cisco.iosxr.iosxr_command:
      commands: show running-config
    register: show_run

  - name: "IOS-XR - Parse interface config info"
    ansible.utils.cli_parse:
      text: "{{ show_run['stdout'] }}"
      parser:
        name: ansible.netcommon.native
        template_path: template.ttp
```

##### EXPECTED RESULTS
Expectation is to obtain array of TTP output, based on template definition.

##### ACTUAL RESULTS
I receive the error "'list' object has no attribute 'splitlines'" when trying to parse that variable of stored output. I tried several variations, like reading from 'stdout_lines' and reading from the first element of each. The documentation states to simply parse the element 'stdout' from the variable.
```
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.iosxr to cisco.iosxr.iosxr
redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr

TASK [IOS-XR - Parse interface config info] ***************************************************************************************************************************************************
task path: /home/refried.jello/playbook.yml:136
fatal: [ncs-5501.company.com]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception from parser 'ansible.netcommon.native'. Error: 'list' object has no attribute 'splitlines'"
}
```

**Comment by refriedjello** [comment]
I was able to get it working using these tasks:

```
  - name: "IOS-XR - Pull running-config"
    cisco.iosxr.iosxr_command:
      commands: show running-config
    register: show_run

  - name: "IOS-XR - Parse interface config info"
    ansible.utils.cli_parse:
      text: "{{ show_run['stdout'][0] }}"
      parser:
        name: ansible.utils.ttp
        template_path: template.ttp
```
