### ISSUE TITLE
Wrong link-local network definition

### ISSUE THREAD

**Issue by guillaumewatteeux** [ansible-collections/ansible.netcommon#343]
##### SUMMARY
https://github.com/ansible-collections/ansible.netcommon/blob/d372fd9c81eb87f41495ebd84ad3f46bbca91eec/plugins/filter/ipaddr.py#L213

Hi,
A correct network for link-local is 169.254.0.0/16 and not 169.254.0.0/24. 

RFC: https://datatracker.ietf.org/doc/html/rfc3927#section-1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.netcommon.ipaddr

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.pyenv/versions/3.8.10/envs/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.pyenv/versions/ansible/bin/ansible
  python version = 3.8.10 (default, Nov 16 2021, 16:31:40) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$> ansible-galaxy collection list ansible.netcommon

# /home/ubuntu/.pyenv/versions/3.8.10/envs/ansible/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.4.0  
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    _ip_addr:
      - "192.168.1.1"
      - "169.254.0.123"
      - "169.254.1.124"
      - 'fe80::100'
  tasks:
    - name: debug
      ansible.builtin.debug:
        var: _ip_addr | ansible.netcommon.ipv4('link-local')
```

##### EXPECTED RESULTS

```
TASK [debug] *********************************************************************************************************************************************************
ok: [localhost] => {
    "_ip_addr | ansible.netcommon.ipv4('link-local')": [
        "169.254.0.123",
        "169.254.1.124"
    ]
}
```

##### ACTUAL RESULTS

```paste below
TASK [debug] *********************************************************************************************************************************************************
ok: [localhost] => {
    "_ip_addr | ansible.netcommon.ipv4('link-local')": [
        "169.254.0.123"
    ]
}
```
