### ISSUE TITLE
unable to load API plugin for platform type ansible.netcommon.restconf

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible-collections/ansible.netcommon#356]
### Summary

Using 'ansible_connection: ansible.netcommon.httpapi' with 'ansible_network_os: ansible.netcommon.restconf' fails with [ansible.netcommon.restconf_get](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/restconf_get_module.html#notes).

### Issue Type

Bug Report

### Component Name

restconf_get

### Ansible & deps Versions

```console
$ ansible --version
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /opt
  executable location = /usr/local/bin/ansible
  python version = 3.9.9 (main, Jan 12 2022, 16:10:51) [GCC 11.2.0]
  jinja version = 3.0.1
  libyaml = True
$ ansible-galaxy collection list --server release_galaxy ansible.netcommon

$ /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.5.0  
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:<port>:0:<password>
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 259200
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/opt']
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = replace
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

Ubuntu 21.10 impish

### Steps to Reproduce

playbook:
```
- name: Getting RESTConf API root
  hosts:
        - all
  vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: ansible.netcommon.restconf
  tasks:
        - name: Getting api root
          ansible.netcommon.restconf_get:
                content: "all"
                output: "xml"
                path: "/.well-known/host-meta"
```

### Expected Results

The following should be returned:
```
<XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>
    <Link rel='restconf' href='/restconf'/>
</XRD>
```

### Actual Results
Running the previous playbook over csr1k 17.3.1a leads to:

```
fatal: [CSR1000v-17.3.1a]: FAILED! => 
  msg: unable to load API plugin for platform type ansible.netcommon.restconf
```

@ganeshrn 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
