### ISSUE TITLE
Authentication issue starting from 3.0.1

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/ansible.netcommon#450]
##### SUMMARY

running simple playbook to backup CIsco IOS switch config getting error:

ssh connection failed: Failed to authenticate public key: Access denied for 'publickey'. Authentication that can continue: publickey,keyboard-interactive,password

the same playbook works fine with netcommon version 3.0.0

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/alv_py39/lib64/python3.9/site-packages/ansible
  ansible collection location = /var/lib/awx/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/lib/awx/venv/alv_py39/bin/ansible
  python version = 3.9.6 (default, Aug 25 2021, 16:22:38) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /var/lib/awx/venv/alv_py39/lib64/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 3.0.1  

# /var/lib/awx/venv/alv_py39/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 3.0.1  

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

15.2(7)E2, RELEASE SOFTWARE (fc3) 

##### STEPS TO REPRODUCE

```yaml
 - name: Test
   hosts: test_switch
   connection: network_cli
   tasks:
         - name: Backup current Switches config
           cisco.ios.ios_config:
             backup: true
             backup_options:
               filename: "{{ inventory_hostname }}.cfg"
               dir_path: /tmp
           register: backup_status
```

##### EXPECTED RESULTS

expected config backup

##### ACTUAL RESULTS

```paste below
ssh connection failed: Failed to authenticate public key: Access denied for 'publickey'. Authentication that can continue: publickey,keyboard-interactive,password

```
