### ISSUE TITLE
Documentation Example Errors: ansible.netcommon.telnet

### ISSUE THREAD

**Issue by brianlturney** [ansible-collections/ansible.netcommon#459]
##### SUMMARY

The example results with error. ansible.netcommon.telnet module attempts ssh connection.
```
fatal: [10.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 10.0.0.1 port 22: Connection refused", "unreachable": true}
```
- Confirmed manual telnet connection/login are successful from ansible controller to target.
- Ping results to 10.0.0.1 confirmed successful.

##### ISSUE TYPE
- Documentation Report
Update the docs with correct examples.
##### COMPONENT NAME
```
- name: run show commands
  ansible.netcommon.telnet:
    user: cisco
    password: cisco
    login_prompt: 'Username: '
    prompts:
    - '[>#]'
    command:
    - terminal length 0
    - show version
```
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/administrator/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/administrator/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.10 (main, Feb  9 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 2.11.3
  libyaml = True

```
