### ISSUE TITLE
Initializing SCP session of remote file for write failed with error [b'Socket error: Success']

### ISSUE THREAD

**Issue by IzxxY** [ansible-collections/ansible.netcommon#484]
##### SUMMARY

I'm trying to upgrade the IOS on my cisco switch with an ansible playbook.

When I try to launch this task :
 
```
- name: COPY IOS
  ansible.common.net_put:
    src: "~/GitLab/ansible-roles/cisco-upgrade-2960S/files/c2960s-universalk9-mz.152-2.E9.bin"
    dest: "flash:/c2960s-universalk9-mz.152-2.E9.bin"
    protocol: scp
    
```

It fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module ansible.netcommon (net_put)
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /home/at/GitLab/ansible-playbooks/cisco/ansible.cfg
  configured module search path = ['/home/at/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/at/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Apr  5 2022, 08:07:47) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10.0.1)]
  jinja version = 2.10.3
  libyaml = True

```

##### COLLECTION VERSION

```
at@srv-ansible cisco]$ ansible-galaxy collection list ansible.netcommon

# /usr/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.5.1

# /home/at/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 4.1.0
[at@srv-ansible cisco]$ ansible-galaxy collection list cisco.ios

# /usr/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.7.1

# /home/at/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  4.0.0


```

##### CONFIGURATION

```
DEFAULT_LOG_PATH(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = /home/at/ansible.log
DEFAULT_MANAGED_STR(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = Ansible managed /!\ do not edit
DEFAULT_REMOTE_USER(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = ['/home/at/GitLab/ansible-playbooks/cisco/roles', '/home/at>
DEFAULT_TIMEOUT(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = 90
DEFAULT_VAULT_PASSWORD_FILE(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = /home/at/.vault_pass.txt
DEPRECATION_WARNINGS(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = True
HOST_KEY_CHECKING(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/at/GitLab/ansible-playbooks/cisco/ansible.cfg) = False
```

##### OS / ENVIRONMENT

[at@srv-ansible cisco]$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.6"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.6
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.6

##### STEPS TO REPRODUCE

- Play this playbook on a cisco switch 2960S / IOS:  12.2(55)SE5

```yaml
- name: COLLECT
  cisco.ios.facts:
    gather_subset:
    - min

- name: CHECK
  debug:
          msg:
          - "La version du commutateur est {{ ansible_net_version }}"
          - "La dernière version est {{ last_ios_version }}, le commutateur va donc être mis à jour vers cette version"
  when: ansible_net_version != last_ios_version

- name: COPY
  ansible.netcommon.net_put:
    src: ~/GitLab/ansible-roles/cisco-upgrade-2960S/files/c2960s-universalk9-mz.152-2.E9.bin
    dest: flash:/c2960s-universalk9-mz.152-2.E9.bin
    protocol: scp

```

##### EXPECTED RESULTS

On every website that i'v seen, this net_put module should work.

##### ACTUAL RESULTS

```paste below
TASK [cisco-upgrade-2960S : COPY] *************************************************************************************************
task path: /home/at/GitLab/ansible-roles/cisco-upgrade-2960S/tasks/main.yml:15
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
<10.10.105.232> attempting to start connection
<10.10.105.232> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/bin/ansible-connection
<10.10.105.232> found existing local domain socket, using it!
<10.10.105.232> updating play_context for connection
<10.10.105.232>
<10.10.105.232> local domain socket path is /home/at/.ansible/pc/a8a9396665
Getting network OS from inventory
fatal: [10.10.105.232]: FAILED! => {
    "changed": false,
    "destination": "flash:/c2960s-universalk9-mz.152-2.E9.bin",
    "msg": "Exception received: Error transferring file to flash:/c2960s-universalk9-mz.152-2.E9.bin: Initializing SCP session of remote file [flash:/c2960s-universalk9-mz.152-2.E9.bin] for write failed with error [b'Socket error: Success']"
}

PLAY RECAP ***********************************************************************************************************************************************************
10.10.105.232              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
