### ISSUE TITLE
netconf_config false argument when using confirm_commit

### ISSUE THREAD

**Issue by Dalle55** [ansible-collections/ansible.netcommon#551]
##### SUMMARY
Getting the following error when enabling commit with or without confirm_commit:

false, "msg": "Argument must be bytes or unicode, got 'int'"}

I have seen bug reports on the same on previous ansible version 2.9 and 2.7 - we are on 2.13

it is the waiting time specified under "commit: 10" that fails
But also fails to identify "confirm_commit: true"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netconf_config

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible [core 2.13.4]
python version = 3.8.10
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
ansible.netcommon 3.1.1

```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/voldby/git/SSN-4.9/ssn-4-platform/automation/ansible/configuration/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/voldby/git/SSN-4.9/ssn-4-platform/automation/ansible/configuration/ansible.cfg) = ['/home/voldby/git/SSN-4.9/network-lab-inventory/DKBB2/inventory']
DEFAULT_LOG_PATH(/home/voldby/git/SSN-4.9/ssn-4-platform/automation/ansible/configuration/ansible.cfg) = /home/voldby/git/SSN-4.9/ssn-4-platform/automation/log/ansible overrule ans>
DEFAULT_TIMEOUT(/home/voldby/git/SSN-4.9/ssn-4-platform/automation/ansible/configuration/ansible.cfg) = 5
HOST_KEY_CHECKING(/home/voldby/git/SSN-4.9/ssn-4-platform/automation/ansible/configuration/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible running on: Ubuntu 20.04.5 LTS
target network device: cisco IE-3300-8T2S
target firmware; 17.9.3

target network device support for confirmed_commit

urn:ietf:params:netconf:capability:confirmed-commit:1.1
urn:ietf:params:netconf:capability:confirmed-commit:1.0
urn:ietf:params:netconf:capability:candidate:1.0

##### STEPS TO REPRODUCE

```yaml
- name: Configure /native/ip/domain
  tags:
    - ip
    - domain
  netconf_config:
    target: candidate
    format: xml
    lock: never
    commit: yes
    confirm: 10
    get_filter: "/native/ip/domain"
    content: "{{ lookup('template', 'native_ip_domain.j2') }}"
  register: result
  until: result is not failed
  retries: "{{ DEFAULT_RETRIES }}"
  delay: "{{ DEFAULT_DELAY }}"
```

##### EXPECTED RESULTS

I expected confim_commit succes

##### ACTUAL RESULTS

```paste below
fatal: [DKBB2-SWP-WTG001-NA-SW01]: FAILED! => {"attempts": 5, "changed": false, "msg": "Argument must be bytes or unicode, got 'int'"}
```

**Comment by Dalle55** [comment]
I have also tried the following:

```yaml
- name: Configure devices
  tags: 
    - ip
    - domain
  netconf_config:
    get_filter: "/native/ip/domain"
    content: "{{ lookup('template', 'native_ip_domain.j2') }}"
    format: xml
    target: candidate
    lock: never
    confirm: 10
  register: result
  until: result is not failed
  retries: "{{ DEFAULT_RETRIES }}"
  delay: "{{ DEFAULT_DELAY }}"

- name: Confirm a previous commit
  tags:
    - ip
    - domain
  netconf_config:
    lock: never
    confirm_commit: yes
```
