### ISSUE TITLE
Integrating Commit Comment Support for Nokia SROS Devices in Ansible's netcommon Module

### ISSUE THREAD

**Issue by torkashvand** [ansible-collections/ansible.netcommon#596]
##### SUMMARY
Hello,

I recently contributed a feature to `ncclient` that adds commit comment support for Nokia SROS devices ([PR #574](https://github.com/ncclient/ncclient/pull/574)). While the `commit_comment` capability is not defined in ([RFC 6241](https://www.rfc-editor.org/rfc/rfc6241.html#section-1.3)), it is supported by Nokia SROS devices and with my PR the `ncclient` supports it as well.

I am now considering best integrating this feature with `ansible.netcommon.netconf_config`. My question is whether I should create a separate module for myself with my own namespace for this specific feature and accept the risk of potential deviation from the main `ansible.netcommon.netconf_config `module or if we could incorporate the support directly into netcommon. I would appreciate your guidance on this matter.

Here's where commit_comment capability could go:

([reference](https://github.com/ansible-collections/ansible.netcommon/blob/fada835bb07cae51ecb54291b342d61cdcd2aaaf/plugins/plugin_utils/netconf_base.py#L373)):
```python    

def get_device_operations(self, server_capabilities):
        """
        Retrieve remote host capability from Netconf server hello message.
        :param server_capabilities: Server capabilities received during Netconf session initialization
        :return: Remote host capabilities in dictionary format
        """
        operations = {}
        capabilities = "\n".join(server_capabilities)
        operations["supports_commit"] = ":candidate" in capabilities
        operations["supports_defaults"] = ":with-defaults" in capabilities
        operations["supports_confirm_commit"] = ":confirmed-commit" in capabilities
        operations["supports_startup"] = ":startup" in capabilities
        operations["supports_xpath"] = ":xpath" in capabilities
        operations["supports_writable_running"] = ":writable-running" in capabilities
        operations["supports_validate"] = ":validate" in capabilities

        operations["lock_datastore"] = []
        if operations["supports_writable_running"]:
            operations["lock_datastore"].append("running")

        if operations["supports_commit"]:
            operations["lock_datastore"].append("candidate")

        if operations["supports_startup"]:
            operations["lock_datastore"].append("startup")

        operations["supports_lock"] = bool(operations["lock_datastore"])

        return operations
```

also this file ([netconf_config.py](https://github.com/ansible-collections/ansible.netcommon/blob/fada835bb07cae51ecb54291b342d61cdcd2aaaf/plugins/modules/netconf_config.py#L431))
and this file **([netconf_base.py](https://github.com/ansible-collections/ansible.netcommon/blob/fada835bb07cae51ecb54291b342d61cdcd2aaaf/plugins/plugin_utils/netconf_base.py#L288))**

Thank you,

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.netcommon.netconf_config

##### ADDITIONAL INFORMATION

I changed these files in my local and the  final view would be something like this:
```yaml
---
- hosts: all
  vars:
    - ansible_network_os: nokia.sros.md
    - ansible_port: 830


  connection: netconf
  gather_facts: yes

  collections:
  - nokia.sros

  tasks:
  - name: "configure using direct native format configuration"
    ansible.netcommon.netconf_config:
      format: xml
      default_operation: merge
      content: "{{ lookup('ansible.builtin.template', './templates/nokia/snmp.j2') }}"
      commit: true
      commit_comment: "SNMP configuration by Mohammad as an example commit comment"
    diff: true
    check_mode: false
```
