### ISSUE TITLE
Add support to prettify xml with netconf_config before making diff

### ISSUE THREAD

**Issue by 33Fraise33** [ansible-collections/ansible.netcommon#645]
##### SUMMARY
We have a vendor where the xml is minified to a 1 line xml. If we run netconf_config with `--diff` we are getting the full configuration before and after as the config is only one line and there is a change on that line. 
It would come in handy to pass an option to the module to prettify the xml before taking the diff. This way we can actually have meaningful use of `--diff --check`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.netcommon.netconf_config

##### ADDITIONAL INFORMATION
see summary

```yaml
- name: Nc-cli change netconf server config
  ansible.netcommon.netconf_config:
    content: "{{ lookup('template', 'config_swind_vrf_netconf_server.xml.j2') }}"
```

**Comment by 33Fraise33** [comment]
I was able to implement a workaround even though it is not perfect: 
```
- name: 6WIND - {{ swind_play_name }}
  ansible.netcommon.netconf_config:
    content: "{{ swind_template_content }}"
  no_log: true  # needed to prevent diff output from module, do nut use diff: false as it will not register output
  register: swind_netconf_output
- name: 6WIND - Set diff facts
  ansible.builtin.set_fact:
    netconf_before: "{{ swind_netconf_output.diff.before | ansible.utils.from_xml }}"
    netconf_after: "{{ swind_netconf_output.diff.after | ansible.utils.from_xml }}"
  when: swind_netconf_output.diff is defined
- name: 6WIND - Show diff
  ansible.utils.fact_diff:
    before: "{{ netconf_before | ansible.utils.to_paths }}"
    after: "{{ netconf_after | ansible.utils.to_paths }}"
  when: swind_netconf_output.diff is defined

```

This results in: 
``````
