### ISSUE TITLE
Unable to Execute copy-config RPC with ansible.netcommon.netconf_rpc on NETCONF Server

### ISSUE THREAD

**Issue by jclaerhout** [ansible-collections/ansible.netcommon#688]
I am trying to execute a task using the ansible.netcommon.netconf_rpc module to save the running configuration to the startup configuration on a NETCONF-enabled device. I found this exact task in the Ansible documentation and in the example usage of the module, so I assume the task should work without issues.

Here is the task I am executing:
```
---
- name: Copy running to startup
  ansible.netcommon.netconf_rpc:
    rpc: copy-config
    content:
      source:
        running:
      target:
        startup:
```

However, when I run this task on my NETCONF server, I receive the following error:
`<bad-element>copy-config</bad-element>
`

This suggests that the copy-config RPC is not recognized or supported, despite being listed in the Ansible documentation as a valid operation.

**Expected Behavior**

The task should execute successfully and save the running configuration to the startup configuration on the NETCONF device.

**Actual Behavior**

The task fails with a bad-element error, indicating that the copy-config RPC is not recognized by the server.

**Environment Details**

    Ansible Version: ansible [core 2.15.8]
    Ansible Collection: ansible.netcommon
    NETCONF Server: Cisco IOS XE Software, Version 17.03.05
    Hardware Model: C9300L-48UXG-4X
    Module Used: ansible.netcommon.netconf_rpc
    Connection Type: NETCONF
