### ISSUE TITLE
cli_command doesn't support httpapi

### ISSUE THREAD

**Issue by bewing** [ansible-collections/ansible.netcommon#692]
##### SUMMARY

Attempting to manage Arista EOS devices via httpapi with a configuration change save handler fails, as only `network_cli` modules are supported per https://github.com/ansible-collections/ansible.netcommon/blob/main/plugins/action/cli_command.py#L18

However, Arista does have limited support for CLI actions as httpapi.get is defined:

https://github.com/ansible-collections/arista.eos/blob/main/plugins/httpapi/eos.py#L153

The check should be updated to see if the module has a "get" method, not checking the name of the module itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.netcommon.cli_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.3]
  config file = None
  configured module search path = ['/home/bewing/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bewing/.local/share/uv/tools/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/bewing/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/bewing/.local/bin/ansible
  python version = 3.11.11 (main, Mar 17 2025, 21:02:09) [Clang 20.1.0 ] (/home/bewing/.local/share/uv/tools/ansible/bin/python)
  jinja version = 3.1.6
  libyaml = True

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
$ ansible-galaxy collection list ansible.netcommon

# /home/bewing/.local/share/uv/tools/ansible/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 7.1.0

```

##### OS / ENVIRONMENT

WSL2 running Ubuntu 22.04 jammy

##### STEPS TO REPRODUCE

```yaml
tasks: 
- name: Push NTP config
  ansible.netcommon.network_resource:
    name: ntp_global
    config: "{{ ntp_config | to_json }}"
    state: overridden
  notify: Save config
handlers:
- name: Save config
  ansible.netcommon.cli_command:
    command: copy running-config startup-config
```

##### EXPECTED RESULTS

Arista device using httpapi connection module saves configuration on change

##### ACTUAL RESULTS

```
<!--- Paste verbatim command output between quotes -->
```paste below
{"changed": false, "msg": "Connection type ansible.netcommon.httpapi is not valid for this module"}
```
