### ISSUE TITLE
cli_command does not return full output (stdout) when error is raised, msg is truncated

### ISSUE THREAD

**Issue by kris-81** [ansible-collections/ansible.netcommon#704]
##### SUMMARY

When using a list of commands generating large output, full output won't be returned if an error is raised, only a msg variable with a truncated output (270 chars), even if we use ignore_errors: true

This issue is really impacting as we have no solution to get or log the output of what have been executed previously when an error is raised

output (router name has been replaced in the output):
```
{
  "msg": "Router(config)#command_to_fail\r\n ^\r\n% Invalid input detected at '^' marker.\r\n\r\nRouter(config)#vrf definition TEST-FAIL-AWX\r\nRouter(config-vrf)#rd 56:9323\r\nRouter(config-vrf)#",
  "invocation": {
    "module_args": {
      "command": "show ip int brie\nshow interfaces\nconf t\ncommand_to_fail\nvrf definition TEST-FAIL-AWX\nrd 56:9323",
      "newline": true,
      "sendonly": false,
      "check_all": false,
      "prompt": null,
      "answer": null
    }
  },
  "_ansible_no_log": false,
  "changed": false
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cli_command

##### ANSIBLE VERSION
2.16.14

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: Send commands to device
      ansible.netcommon.cli_command:
        command: "{{ _list_of_commands_to_execute }}"
      register: command_result
```

##### EXPECTED RESULTS

full stdout should always be returned

##### ACTUAL RESULTS

```paste below

```
