### ISSUE TITLE
httpapi checkpoint connection cannot specific domain

### ISSUE THREAD

**Issue by Arenaos** [ansible-collections/ansible.netcommon#71]
##### SUMMARY

Previously open a issue on wrong repo https://github.com/ansible/ansible/issues/70362 Been redirected here by @mkrizek .
I'dont find any solution to specify a domain to connect on.

What is the var to use to specify wich domain (mds solution checkpoint).

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
Ansible 2.9.5
```

##### STEPS TO REPRODUCE

```
---
- name: example_playbook
  hosts: all
  connection: httpapi
  tasks:
    - name: show-host
      cp_mgmt_host_facts:
        name: exemple_srv

INVENTORY

---
ansible_checkpoint_domain: domain   <--- THIS IS THE VAR I CANNOT FIND
ansible_network_os: checkpoint
ansible_user: user
ansible_password: pwd
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False

```

##### EXPECTED RESULTS

Var to specify the multi domain server name for CheckPoint R80.40

##### ACTUAL RESULTS

```
"OBJECTS NOT FOUND" because ansible module checkpoint python don't specify domain.
If i use mds facts module, everything works fine.

```
