### ISSUE TITLE
command timeout triggered, timeout value is 30 secs failure message using cli_command on dellos10 switch 

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/ansible.netcommon#86]
_From @srivaa31 on Jul 14, 2020 10:33_

##### SUMMARY
shutdown command on switch interface consistently fails with "command timeout triggered, timeout value is 30 secs" message 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cli_command module
##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below
DEFAULT_PRIVATE_KEY_FILE(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_REMOTE_USER(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = root
DISPLAY_SKIPPED_HOSTS(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = False
HOST_KEY_CHECKING(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = False
INTERPRETER_PYTHON(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = auto

```

##### OS / ENVIRONMENT

CentOS Linux release 8.1.1911 (Core)

##### STEPS TO REPRODUCE

switch_shutdown.yml 
```yaml
---
- name: shutdown same ports on all switches
  debug:
    msg: "Shutdown test case "

- name: Add config mode as first command
  set_fact:
    cli_switch_commands:
      - config

- name: Add commands for each port shutdown
  vars:
    current_port_command: "interface Tengigabitethernet 0/{{ item }}"
  set_fact:
    cli_switch_commands: "{{ cli_switch_commands + [current_port_command, 'shutdown'] }}"
  loop: "{{ shutdown_ports }}"

- name: Send all commands to switch
  debug:
    msg: "{{item}}"
  loop: "{{ cli_switch_commands }}"

- name: sending....
  cli_command:
    command: "{{ item }}"
  loop: "{{ cli_switch_commands }}"
  delegate_to: TOR_A


```
switch.yml <- playbook file 
```yaml
---
- name: Shutdown ports on TOR switches
  hosts: switches
  gather_facts: false
  roles:
     - switch_test

```
switch_test is the role file 
task file is switch_shutdown.yml

Content of hosts file below
/etc/ansible/hosts 
```txt
[switches]
TOR_A ansible_host=100.80.81.248 ansible_user=admin ansible_pass=Raid4us! ansible_connection=network_cli ansible_network_os=dellos10 ansible_become=yes ansible_become_method=enable ansible_command_timeout=30
```

##### EXPECTED RESULTS

Successful login to switch and shut down of specified port

##### ACTUAL RESULTS

```paste below
failed: [TOR_A -> 100.80.81.248] (item=config) => {"ansible_loop_var": "item", "changed": false, "item": "config", "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}
failed: [TOR_A -> 100.80.81.248] (item=interface Tengigabitethernet 0/34) => {"ansible_loop_var": "item", "changed": false, "item": "interface Tengigabitethernet 0/34", "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}
failed: [TOR_A -> 100.80.81.248] (item=shutdown) => {"ansible_loop_var": "item", "changed": false, "item": "shutdown", "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}
```

_Copied from original issue: ansible/ansible#70633_
